In [60]:
import pandas as pd
import os
from pymongo import MongoClient
import subprocess
import shutil

In [34]:
ignore_file_list = [
    'favorites.bson',
    'projects.bson',
    'talk.bson',
    'users.bson',
    'boards.bson'
]
base_dir = r'/srv/zooniverse/raw_data/ouroboros/ouroboros_2016-08-11'

infile_list = [x for x in os.listdir(base_dir) if x not in ignore_file_list]
for infile in infile_list:
    collection_name = infile.replace('.bson','')
    infile_path = os.path.join(base_dir,infile)
    print('importing {0} to {1}'.format(infile_path,collection_name))
    subprocess.run(['mongorestore','-d','zooniverse','-c',collection_name,infile_path])
    break

importing /srv/zooniverse/raw_data/ouroboros/ouroboros_2016-08-11/andromeda_classifications.bson to andromeda_classifications

In [41]:
fieldfile = r'/home/sjm668/dev/zooniverse/src/classification_fields.txt'
outdir = r'/srv/zooniverse/tables'

client = MongoClient()
collections_list = client['zooniverse'].collection_names()
tempdir = os.path.join(outdir,'temp')
if not os.path.exists(tempdir):
    os.mkdir(tempdir)
for collection in collections_list:
    temp_outfile = os.path.join(tempdir,'{0}.csv'.format(collection))
    print('exporting {0} to {1}'.format(collection,temp_outfile))
    subprocess.run(['mongoexport','-d','zooniverse','-c',collection,'--fieldFile',fieldfile,'--type=csv','--out',temp_outfile])
    break

exporting worms_classifications to /srv/zooniverse/tables/temp/worms_classifications.csv

In [62]:
project_df_path = '/srv/zooniverse/tables/mongo_project_table_03-02-17.csv'
project_df = pd.read_csv(project_df_path)

,_id,activated_subjects_at,classification_count,complete_count,created_at,display_name,name,panoptes_id,site_prefix,user_count,zooniverse_id
0,ObjectId(4fdf8fb3c32dab6c95000001),2017-01-30T08:00:38.772Z,2609692,123085.0,2012-09-12T19:30:15.838Z,Seafloor Explorer,sea_floor,35.0,SF,24053.0,15
1,ObjectId(4fff255d516bcb407b000001),2017-01-30T08:00:38.799Z,568967,163850.0,2012-09-30T23:05:30.952Z,Bat Detective,bat_detective,37.0,BD,4928.0,17
2,ObjectId(502a701d516bcb0001000001),2017-01-30T08:00:39.058Z,78543,NaN,2012-09-10T18:40:05.269Z,Galaxy Zoo Quiz,galaxy_zoo_quiz,21.0,GQ,32879.0,21
3,ObjectId(502a90cd516bcb060c000001),2017-01-30T08:00:45.339Z,24920000,763694.0,2012-09-10T18:40:05.260Z,Galaxy Zoo,galaxy_zoo,21.0,GZ,152302.0,1
4,ObjectId(503293e6516bcb6782000001),2017-01-30T08:00:56.846Z,635686,27905.0,2012-09-26T18:54:39.425Z,Cyclone Center,cyclone_center,36.0,CC,13232.0,16
5,ObjectId(5040d826a7823f1d95000001),2017-01-30T08:00:38.839Z,2630537,360611.0,2012-10-23T17:22:13.861Z,Cell Slider,cancer_cells,38.0,CS,23092.0,18
6,ObjectId(5077375154558fabd7000001),2017-01-30T08:01:00.016Z,22477303,2647927.0,2012-12-10T19:28:04.438Z,Snapshot Serengeti,serengeti,40.0,SG,51232.0,20
7,ObjectId(507edef23ae74020d6000001),2017-01-30T08:00:40.556Z,1926577,38764.0,2012-12-04T19:27:41.983Z,Andromeda Project,andromeda,39.0,AP,10715.0,19
8,ObjectId(50e9e3d33ae740f1f3000001),2017-01-30T08:00:40.698Z,5151283,98052.0,2013-01-06T21:54:57.178Z,Planet Four,planet_four,41.0,PF,56925.0,21
9,ObjectId(5101a1341a320ea77f000001),2017-01-30T08:00:40.693Z,18378352,508036.0,2013-05-06T19:57:14.734Z,Space Warps,spacewarp,43.0,SW,29044.0,23
10,ObjectId(511410da3ae740c3ec000001),2017-01-30T08:00:40.779Z,1011391,234945.0,2013-04-18T18:34:27.490Z,Notes From Nature,notes_from_nature,42.0,NN,9273.0,22
11,ObjectId(5154abce3ae740898b000001),2017-01-30T08:00:40.809Z,40947,1839.0,2013-07-08T19:08:36.855Z,MicroPlants,leaf,44.0,LF,224.0,44
12,ObjectId(516d6f243ae740bc96000001),2017-01-30T08:00:39.125Z,1313358,109389.0,2013-09-13T20:22:37.622Z,Plankton Portal,plankton,46.0,PK,10404.0,26
13,ObjectId(51c1c9523ae74071c0000001),2017-01-30T08:00:41.637Z,5278663,211056.0,2014-02-24T21:34:24.760Z,Sunspotter,sunspot,51.0,SZ,12721.0,31
14,ObjectId(51c9bba83ae7407725000001),2017-01-30T08:00:39.182Z,675803,74032.0,2013-06-25T18:59:00.472Z,Worm Watch Lab,worms,45.0,WS,11984.0,25
15,ObjectId(51e6fcdd3ae74023b9000001),2017-01-30T08:00:39.009Z,121580,6080.0,2013-07-18T15:01:23.408Z,Galaxy Zoo Starburst,galaxy_zoo_starburst,21.0,GS,1693.0,21
16,ObjectId(523c78e23ae7403f53000001),2017-01-30T08:00:40.386Z,3118362,94034.0,2014-01-27T18:58:44.076Z,Play to Cure: Genes in Space,cancer_gene_runner,38.0,CG,52365.0,38
17,ObjectId(523ca1a03ae74053b9000001),2017-01-30T08:00:40.644Z,2089420,134058.0,2013-12-10T17:56:45.420Z,The Milky Way Project,milky_way,27.0,MW,17271.0,7
18,ObjectId(528ceac53ae7409ca0000001),2017-01-30T08:00:40.350Z,2664794,182628.0,2014-06-23T15:38:53.876Z,Asteroid Zoo,asteroid,53.0,AZ,12333.0,33
19,ObjectId(52afdb804d69636532000001),2017-01-30T08:00:38.918Z,1858279,121042.0,2013-12-17T05:05:30.935Z,Radio Galaxy Zoo,radio,47.0,RG,10351.0,27
20,ObjectId(52d065303ae740380a000001),2017-01-30T08:00:50.151Z,794531,167080.0,2014-01-11T16:22:27.141Z,War Diaries,war_diary,48.0,WD,14831.0,28
21,ObjectId(52d1718e3ae7401cc8000001),2017-01-30T08:00:39.118Z,52258,2610.0,2014-01-11T16:31:34.977Z,Star Date: M83,m83,49.0,M8,1194.0,29
22,ObjectId(52e2cba83ae7401db5000001),2017-01-30T08:01:37.732Z,452787,60365.0,2014-04-14T18:47:24.279Z,Condor Watch,condor,52.0,CW,5184.0,32
23,ObjectId(52e2cfc1806ea54590000001),2017-01-30T08:00:39.207Z,2165223,130790.0,2014-01-24T21:04:29.719Z,Disk Detective,wise,50.0,WI,11130.0,30
24,ObjectId(5333063b3ae740228a000001),2017-01-30T08:00:40.857Z,8806086,NaN,2014-09-15T16:02:05.598Z,Planet Hunters,planet_hunter,26.0,PH,43181.0,6
25,ObjectId(536d226d3ae740fd20000001),2017-01-30T08:00:40.343Z,2779335,670185.0,2014-08-07T14:50:12.882Z,Kelp,kelp,54.0,KP,6841.0,34
26,ObjectId(53bcf59d06715eba9a000001),2017-01-30T08:00:40.838Z,4758378,258871.0,2014-09-15T20:54:54.012Z,Hard Cell,hard_cell,38.0,HC,NaN,38
27,ObjectId(53c3e9090ab4c05d28000001),2017-01-30T08:00:39.013Z,11275,55.0,2014-07-14T15:16:52.492Z,The Impossible Line,impossible_line,38.0,IL,NaN,38
28,ObjectId(53c94845edf877f277000001),2017-01-30T08:00:40.679Z,1019,16.0,2014-12-08T20:08:21.384Z,Snapshot Wisconsin,wisconsin,NaN,WZ,14.0,0
29,ObjectId(5410f2c03ae740bdc0000001),2017-01-30T08:00:40.553Z,2994143,767860.0,2014-09-11T01:01:15.738Z,Chicago Wildlife Watch,chicago,57.0,CH,8361.0,37
30,ObjectId(54115cd012fc4d17e2000001),2017-01-30T08:00:43.682Z,4647016,513642.0,2014-09-15T11:13:53.193Z,Penguin Watch,penguin,55.0,PZ,39419.0,35
31,ObjectId(545b9c49b0c7823037000001),2017-01-30T08:00:40.283Z,1372716,19083.0,2014-11-06T16:06:22.131Z,Higgs Hunters,higgs_hunter,56.0,HH,10625.0,36
32,ObjectId(54cd1c8761cd3599c4000001),2017-01-30T08:00:40.808Z,32932,NaN,2015-02-10T17:31:52.934Z,Craters,crater,NaN,CR,703.0,0
33,ObjectId(54f42c0ab35d2e06bd000001),2017-01-30T08:00:41.063Z,537994,151952.0,2015-03-02T09:23:53.622Z,Science Gossip,illustratedlife,58.0,SC,9136.0,38
34,ObjectId(551d8b5c61cd354e3c000001),2017-01-30T08:00:42.578Z,2806940,497069.0,2015-04-02T18:37:38.434Z,Chimp & See,chimp,60.0,CP,8532.0,41
35,ObjectId(5527cafa38d2313a2a000001),2017-01-30T08:00:40.288Z,53498,5129.0,2015-04-10T13:07:06.937Z,Orchid Observers,orchid,59.0,ZO,1868.0,40

In [74]:
project_df_path = '/srv/zooniverse/tables/mongo_project_table_03-02-17.csv'

tempdir = os.path.join(outdir,'temp')
infile_list = os.listdir(tempdir)
outfile = pd.DataFrame()
project_df = pd.read_csv(project_df_path)
for infile in infile_list:
    project_title = infile.rsplit('_',1)[0]
    df = pd.read_csv(os.path.join(tempdir,infile))
    print(project_title)
    df['project_name'] = project_title
    try:
        df['project_id'] = project_df.loc[project_df['name'] == project_title,'_id'].values[0]
    except IndexError:
        print('no project {0}'.format(infile.replace('.csv','')))
    break
    #outfile = outfile.append(df)

/home/sjm668/dev/zooniverse/src/venv/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

worms

In [75]:
df['project_id']

0         ObjectId(51c9bba83ae7407725000001)
1         ObjectId(51c9bba83ae7407725000001)
2         ObjectId(51c9bba83ae7407725000001)
3         ObjectId(51c9bba83ae7407725000001)
4         ObjectId(51c9bba83ae7407725000001)
5         ObjectId(51c9bba83ae7407725000001)
6         ObjectId(51c9bba83ae7407725000001)
7         ObjectId(51c9bba83ae7407725000001)
8         ObjectId(51c9bba83ae7407725000001)
9         ObjectId(51c9bba83ae7407725000001)
10        ObjectId(51c9bba83ae7407725000001)
11        ObjectId(51c9bba83ae7407725000001)
12        ObjectId(51c9bba83ae7407725000001)
13        ObjectId(51c9bba83ae7407725000001)
14        ObjectId(51c9bba83ae7407725000001)
15        ObjectId(51c9bba83ae7407725000001)
16        ObjectId(51c9bba83ae7407725000001)
17        ObjectId(51c9bba83ae7407725000001)
18        ObjectId(51c9bba83ae7407725000001)
19        ObjectId(51c9bba83ae7407725000001)
20        ObjectId(51c9bba83ae7407725000001)
21        ObjectId(51c9bba83ae7407725000001)
22        ObjectId(51c9bba83ae7407725000001)
23        ObjectId(51c9bba83ae7407725000001)
24        ObjectId(51c9bba83ae7407725000001)
25        ObjectId(51c9bba83ae7407725000001)
26        ObjectId(51c9bba83ae7407725000001)
27        ObjectId(51c9bba83ae7407725000001)
28        ObjectId(51c9bba83ae7407725000001)
29        ObjectId(51c9bba83ae7407725000001)
                         ...
704035    ObjectId(51c9bba83ae7407725000001)
704036    ObjectId(51c9bba83ae7407725000001)
704037    ObjectId(51c9bba83ae7407725000001)
704038    ObjectId(51c9bba83ae7407725000001)
704039    ObjectId(51c9bba83ae7407725000001)
704040    ObjectId(51c9bba83ae7407725000001)
704041    ObjectId(51c9bba83ae7407725000001)
704042    ObjectId(51c9bba83ae7407725000001)
704043    ObjectId(51c9bba83ae7407725000001)
704044    ObjectId(51c9bba83ae7407725000001)
704045    ObjectId(51c9bba83ae7407725000001)
704046    ObjectId(51c9bba83ae7407725000001)
704047    ObjectId(51c9bba83ae7407725000001)
704048    ObjectId(51c9bba83ae7407725000001)
704049    ObjectId(51c9bba83ae7407725000001)
704050    ObjectId(51c9bba83ae7407725000001)
704051    ObjectId(51c9bba83ae7407725000001)
704052    ObjectId(51c9bba83ae7407725000001)
704053    ObjectId(51c9bba83ae7407725000001)
704054    ObjectId(51c9bba83ae7407725000001)
704055    ObjectId(51c9bba83ae7407725000001)
704056    ObjectId(51c9bba83ae7407725000001)
704057    ObjectId(51c9bba83ae7407725000001)
704058    ObjectId(51c9bba83ae7407725000001)
704059    ObjectId(51c9bba83ae7407725000001)
704060    ObjectId(51c9bba83ae7407725000001)
704061    ObjectId(51c9bba83ae7407725000001)
704062    ObjectId(51c9bba83ae7407725000001)
704063    ObjectId(51c9bba83ae7407725000001)
704064    ObjectId(51c9bba83ae7407725000001)
Name: project_id, dtype: object

In [59]:
os.path.dirname(fieldfile)

'/home/sjm668/dev/zooniverse/src'